version: '3'

services:
  lumen-api:
    build: .
    ports:
      - "8082:80"
    volumes:
      - ./:/usr/share/nginx
    networks:
        - app-network

  mysql:
    image: mysql:5.7
    ports: 
      - "3307:3306"
    volumes:
      - .docrker/db_data:/var/lib/mysql
    
    environment:
      MYSQL_DATABASE: mysqlDb
      MYSQL_ROOT_PASSWORD: cpassos
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    
           